### ISSUE TITLE
Init Checklist

### ISSUE THREAD

**Issue by Zoidmania** [Zoidmania/tome2#1]
A short to-do list to get started:

- [x] uWSGI, Nginx, and Certbot configuration instructions
- [x] Django SSL config instructions
- [x] Travis CI setup
- [x] Coveralls setup
- [ ] add initial reference data models
- [ ] add testing functions for data models
- [ ] add character tracking models
- [ ] add testing functions for character models
- [ ] add `django-taggit` after models are built (considering using it for convenience)
- [ ] add `django-haystack` and `Whoosh` for a simple search index after models are built
- [x] add basic templates for planned pages (build out later)
- [ ] add browsing UI for all reference data models
- [ ] add character manager UI
- [ ] add function to load data from an external source (likely a flat-file database I keep out of the public reach)
- [ ] add function to serialize data to an external entity (likely the same flat-file format)

**Comment by Zoidmania** [comment]
Finishing the semester; will resume this once school is over.

**Comment by Zoidmania** [comment]
Note to self: add the following to the spell list: 

- [ ] pagination
- [ ] school of magic column
- [ ] filter for casting classes (not shown)
